# Build Stage
FROM node:18-alpine AS build-stage

WORKDIR /app

COPY package*.json ./
RUN yarn

COPY . .
RUN yarn build

# Production Stage
FROM node:18-alpine AS production

WORKDIR /app

COPY --from=build-stage /app/dist ./dist
COPY package*.json ./
RUN yarn install --production

CMD ["node", "dist/main"]
