# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

COPY ./nest-app ./nest-app
COPY package*.json ./
COPY ./yarn.lock ./yarn.lock

# Install application dependencies
RUN yarn

# Copy the rest of the application code to the working directory
COPY . .

WORKDIR /app/nest-app

# Define the command to start your application
CMD ["yarn", "start:dev"]